name             'anaconda'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures anaconda'
long_description 'Installs/Configures anaconda'
version          '0.1.0'
